<a href="https://colab.research.google.com/github/ashwinitadkale/ipl-analysis/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a=int(input())
b=int(input())
rand_arr=np.random.rand(a,b)
print(rand_arr)
avg=np.mean(rand_arr)
print(avg)

2
3
[[0.20304337 0.41431621 0.22691683]
 [0.27688715 0.01269495 0.10988541]]
0.20729065233539798


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def border_arr(a,b):
  arr=np.zeros((a,b),dtype=int)
  arr[0,:]=1
  arr[-1,:]=1
  arr[:,0]=1
  arr[:,-1]=1
  return arr
result=border_arr(5,5)
print(result)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
arr=np.linspace(0,1,12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
i=np.eye(3,4)
# i=np.diag([1,1,1,1])
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
arr=np.tile(np.arange(5),(5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
points=np.random.randint(1,101,(10,2))
point=np.array([2,3])
dist = np.sqrt(np.sum((points - point)**2, axis=1)).astype(int)
print(points)
print(dist)

[[84 37]
 [32 39]
 [49  5]
 [61 16]
 [21 80]
 [62 71]
 [37 11]
 [61 87]
 [34 26]
 [42  2]]
[ 88  46  47  60  79  90  35 102  39  40]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
arr=np.array(input().split(),dtype=float)
print(arr[::-1])

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [4]:
arr=np.array([9,2,3,1])
print('elements_count:',arr.size)

elements_count: 4


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [7]:
import numpy as np

def softmax(arr):
    if not isinstance(arr, np.ndarray) or arr.ndim != 1:
        raise ValueError("Input must be 1D numpy array")

    exp = np.exp(arr - np.max(arr))  # stability trick
    return exp / np.sum(exp)

# Example
print(softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [9]:
def vstack_arrays(*arrays):
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise ValueError("All inputs must be numpy arrays")
    return np.vstack(arrays)

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [12]:
def date_array(start,end):
  if not isinstance(start,str) or not isinstance(end,str):
    raise ValueError("Inputs must be strings")
  dates=np.arange(start,end,dtype='datetime64[D]')
  return np.append(dates,np.datetime64(end))
print(date_array(start = '2020-11-25', end = '2020-11-30'))

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [13]:
arr=np.random.randint(1,10,(3,3))
res=arr-arr.mean(axis=1,keepdims=True)
print(res)

[[-2.66666667 -2.66666667  5.33333333]
 [ 1.33333333 -2.66666667  1.33333333]
 [-1.33333333  2.66666667 -1.33333333]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [19]:
arr=np.random.randint(1,15,(4,3))
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[ 2  2 14]
 [ 9 13  5]
 [13  4  6]
 [12  4  1]]
[[ 2  2 14]
 [13  9  5]
 [ 4 13  6]
 [ 4 12  1]]


###`Q-16:` Replace odd elements in arrays with -1.

In [24]:
arr=np.random.randint(1,15,(4,3))
print(arr)
arr[arr%2!=0]=-1
print(arr)

[[14  4  6]
 [ 5 11 12]
 [ 2 11  4]
 [ 6  6 11]]
[[14  4  6]
 [-1 -1 12]
 [ 2 -1  4]
 [ 6  6 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [25]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
print(np.maximum(a,b))

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [26]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8451, 6211, 1146, 8228, 4467],
       [7774, 1522, 2771, 3797, 9547],
       [8622, 2262, 8866, 4747, 3631],
       [1810, 6411, 6764, 3284,   21],
       [3976, 1446, 6531, 2278, 2152],
       [ 140, 1959, 5063, 6718, 4806],
       [ 276, 4470, 2610, 3287, 8338],
       [ 674,  208, 9025, 6166, 4247]])

In [28]:
arr1[:,::2] #alternate column

array([[8451, 1146, 4467],
       [7774, 2771, 9547],
       [8622, 8866, 3631],
       [1810, 6764,   21],
       [3976, 6531, 2152],
       [ 140, 5063, 4806],
       [ 276, 2610, 8338],
       [ 674, 9025, 4247]])

In [30]:
norm=(arr1-arr1.min())/(arr1.max()-arr1.min())
norm

array([[0.88494646, 0.64980055, 0.11809784, 0.86153685, 0.46672265],
       [0.81387781, 0.15756876, 0.2886836 , 0.39638883, 1.        ],
       [0.90289733, 0.23525089, 0.92851144, 0.49611589, 0.37896284],
       [0.18780181, 0.67079572, 0.70785219, 0.34253622, 0.        ],
       [0.41517951, 0.14959059, 0.68339282, 0.23693051, 0.22370355],
       [0.01249213, 0.20344321, 0.52928826, 0.7030233 , 0.50230947],
       [0.02676884, 0.46703758, 0.27178249, 0.34285114, 0.87308419],
       [0.06854923, 0.01963048, 0.9452026 , 0.64507663, 0.44362797]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [31]:
def nth_largest(arr,n):
  return np.sort(arr)[-n]
print(nth_largest((12,34,40,7,1,0),4))

7


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [32]:
a=np.array([1,2,3])
part1=np.repeat(a,3)
part2=np.tile(a,3)
result=np.concatenate([part1,part2])
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
